medicalAid2/medicalAid2/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

medicalAid2/urls.py
from django.contrib import admin
from django.urls import path, include
from aidApp import views as aid_app_views
from users import views as v

app_name= 'aidApp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', aid_app_views.index, name="homepage"),
    path('about-us/', aid_app_views.about_us, name="about-us"),
    path('faq/', aid_app_views.faq, name="faq"),
    path('login/', aid_app_views.login, name="login"),
    path('sign-up/', aid_app_views.sign_up, name="sign-up"),
    path('feedback/', aid_app_views.feedback, name ="feedback"),
    path('feedbacksent/', aid_app_views.feedbacksent, name="feedbacksent"),
    path('feedbackform/', aid_app_views.feedbackform, name="feedbackform"),
    path('aid/', include('aidApp.urls')),
    path('users/', include('users.urls')),
    path('submit-form/', v.submit_register_form, name="register_user"),
    path('submit-login/', v.login_submit, name="login_user"),
    path('login/', v.render_login_page, name="user_login"),
    path('', include(('aidApp.urls', 'aidApp'), namespace='aidApp'))
]

urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('aidApp/', include("aidApp.urls")),

]


from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from aidApp import views as aid_app_views


app_name = 'users'

urlpatterns = [
    path('register/',views.register, name='register'),
    path('login/', views.render_login_page, name='user_login'),
    path('submit-form/', views.submit_register_form, name='register_user'),
    path('submit-login/', views.login_submit, name="login_user"),
    path('', aid_app_views.index, name="homepage"),
    path('index/', views.index, name='index'),
    path('about-us/', views.about_us, name='about-us'),
    path('faq/', views.faq, name="faq"),
    
    

]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
	    model = User
	    fields = ["username", "email", "password1", "password2"]

register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

# Create your views here.
def register(response):
    if response.method == "POST":
	    form = RegisterForm(response.POST)
	    if form.is_valid():
	        form.save()

	    return redirect("/home")
    else:
	    form = RegisterForm()

    return render(response, "register/register.html", {"form":form})

users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.views.decorators.csrf import requires_csrf_token, csrf_protect
from aidApp.models import FAQ
from aidApp.helper import multiple_forms, newsletter_form


# Create your views here.

def index(request):
    return render(request, 'aidApp/index.html')

def about_us(request):
    return render(request, 'aidApp/about-us.html')

def faq(request):

    faqs = FAQ.objects.all()
    context = {
        "faqs": faqs
    }

    newsletter_form(request)

    return render(request, 'aidApp/faq.html', context)

@csrf_protect
def register(request):
    return render(request, 'users/register.html')

@csrf_protect
def submit_register_form(request):
    if request.method == 'POST':
        username = request.POST.get('username', None)
        first_name = request.POST.get('fname', None)  
        last_name = request.POST.get('lname', None) 
        email = request.POST.get('email2', None)
        password = request.POST.get('cpwd', None)
        print(first_name, last_name)
        if User.objects.filter(email = email).exists():
            messages.info(request, 'Email already in use please use another one or login')
            return render(request, 'users/register.html') 
        else:
            user = User.objects.create_user(username=username, email=email, password=password)
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            user = authenticate(username = username, password = password)
            if user is not None:
                login(request,user)
                messages.info(request, {'welcome': request.user.first_name})
                return render(request, 'aidApp/index.html')
            
    else:
        return render(request, 'users/register.html')

  
def render_login_page(request):
    return render(request, 'users/login.html')

def login_submit(request):
    username = request.POST['username']
    password = request.POST['pwd']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request,user)
        messages.info(request, {'welcome': request.user.username})
        return render(request, 'aidApp/index.html')
        
    else:
        return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return redirect('users/login.html')

users/templates/users/homepage.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html>
<h1>Dashboard</h1>
</html>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;700&display=swap');
    </style>
    <link href="https://fonts.google.com/specimen/Lexend+Deca" rel="stylesheet">
    <link rel="stylesheet" href={% static 'users/css/login.css' %}>
    <link href="https://fonts.google.com/specimen/Lexend+Deca" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" 
          crossorigin="anonymous"/>
    <link rel="icon" href= {% static 'users/images/login-images/Group.svg' %} type="image/svg+xml">
    <title>Login Page </title>
</head>
<body>

    <!-- <div class="header">
        <span id="logo2">
            <img class="a-logo" src="./images/login-images/Group.svg">
        </span>
        <div class="text-only">
            <a class="logo2-text" href="#" id="nav-logo2">Empr Medical</a>
        </div>
    </div> -->
    <header>
       
        <div class="navbar">
            <div class="dropdown">
                <button class="dropbtn">
                    <i class="fas fa-bars fa-2x"></i>
                </button>
            
              <div class="dropdown-content">
                    <a href= {% url 'users:index' %}>Home</a>
                    <a href= {% url 'users:about-us' %}>About Us</a>
                    <a href= {% url 'users:faq' %}>FAQ</a>
                    <a href= {% url 'users:user_login' %}>Login</a>
                    <a href= {% url 'users:register' %}>Sign Up</a>
                
              </div>
            </div>
        </div>
        
        
        <a class=logo href="index.html">
            <img src= {% static 'users/images/FAQ-images/Group.svg' %}>&nbsp;
            <h2>Empr Medical</h2>
        </a>

            <div class="no-dropdown">
                    <a href= {% url 'users:index' %}>Home</a>
                    <a href= {% url 'users:about-us' %}>About Us</a>
                    <a href= {% url 'users:faq' %}>FAQ</a>
                    <a href= {% url 'users:user_login' %}>Login</a>
                    <a href= {% url 'users:register' %}>Sign Up</a>
            </div>
                   
        </header>
                <!-- PATIENT/DOCTOR PAGE TAB
                <div class="tab-switch">
                    <div class="tab-wrapper">
                    <ul>
                        <li class="patient-tab"><a class="patient-link" href="registration.html">Patient</a></li>
                        <li class="doc-tab"><a class="doc-link" href="doctorregistration.html">Doctor</a></li>
                    </ul>
                    </div>
                </div> -->


    <div class="flex-container">
        <div class="image">
            <img class="doc2-img" src={% static 'users\images\login-images\Doctor4.svg' %}>  
        </div>

        <div class="container">
            <div class="login-heading">
                <p>Login</p>
            </div>
            
            <form method ="post" action= {% url 'users:login_user' %}>
            {% csrf_token %}
        
                    <input type="username" class="email1" name="username" placeholder="Enter Username" required><br>
                    <input type="password" class="pwd" name="pwd" placeholder="Enter Password" required><br><br>

                    <div  class="move-bx">
                        <input type="checkbox" class="chkbx" name="chkbx">
                        <label for="chkbx" style="font-size: 17px">Remember me</label>
                        <span class="psw"><a href="#" style="font-size: 17px; color: rgb(42, 199, 183);">Forget password?</a></span>
                    </div>

                    <div>
                        <button type="submit" class="login-btn">Login</button><br><br><br>
                       </div>      
                   <div class="register">
                       <label for="cracct">Not register yet?</label>
                   
                       <span class="cracct"><a href="register.html" style="color: rgb(42, 199, 183);">Create An account?</a></span>
                   </div>
                </div>

               
            </form>


        </div>
</div>
   
    <!-- fix -->
</body>
</html>
{% endblock %}

users/templates/users/oldlogin.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;700&display=swap');
    </style>
    <link href="https://fonts.google.com/specimen/Lexend+Deca" rel="stylesheet">
    <link rel="stylesheet" href={% static 'users/css/Login.css' %}>
    <link rel="icon" href= {% static 'users\images\login-images\Group.svg' %} type="image/svg+xml">
    <title>Login Page </title>
</head>
<body>

    <div class="header">
        <span id="logo2">
            <img class="a-logo" src={% static 'users\images\login-images\Group.svg' %}>
        </span>

        <div class="text-only">
            <a class="logo2-text" href="#" id="nav-logo2">Empr Medical</a>
        </div>

    </div>


    <div class="flex-container">
        <div class="image">
            <img class="doc2-img" src={% static 'users\images\login-images\Doctor4.svg' %}>  
        </div>

        <div class="container">
            <div class="login-heading">
                <p>Login</p>
            </div>
            
            <form method ="post" action= {% url 'users:login_user' %}>
            {% csrf_token %}
        
                    <input type="username" class="email1" name="username" placeholder="Enter Username" required><br>
                    <input type="password" class="pwd" name="pwd" placeholder="Enter Password" required><br><br>

                    <div  class="move-bx">
                        <input type="checkbox" class="chkbx" name="chkbx">
                        <label for="chkbx" style="font-size: 17px">Remember me</label>
                        <span class="psw"><a href="#" style="font-size: 17px; color: rgb(42, 199, 183);">Forget password?</a></span>
                    </div>

                    <div>
                        <button type="submit" class="login-btn">Login</button><br><br><br>
                       </div>      
                   <div class="register">
                       <label for="cracct">Not register yet?</label>
                   
                       <span class="cracct"><a href="register.html" style="color: rgb(42, 199, 183);">Create An account?</a></span>
                   </div>
                </div>

               
            </form>


        </div>
</div>
   
    <!-- fix -->
</body>
</html>
{% endblock %}

users/templates/users/oldregister.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;700&display=swap');
    </style>
    <link rel="stylesheet" href= {% static 'users/css/registration.css' %}>
    <link rel="icon" href= {% static 'users\images\registration-image\Group.svg' %} type="image/svg">
    <title> 
        Registration Page </title>
</head>
<body>

   <div class="header">
        <span id="logo">
            <img class="a" src={% static 'users\images\registration-image\Group.svg' %}>
        </span>

        <div class="text-only">
            <a class="logo-text" href="#" id="nav-logo">Empr Medical</a>
        </div>

    </div>         

    <div class="flex-container">
        <div class="image">
            <img class="doc-img" src={%static "users\images\registration-image\Doctor4.svg" %}>
        </div>
        
       
            <div class="container">
                <div class="signup-heading">
                    <p>Sign Up</p>
                </div>
        
                
                <form method="post" action= {% url 'users:register_user' %}> 
                {% csrf_token %}
                

                    <div class="name-container">
                        <input type="text" class="fname" name="fname" placeholder="First Name" required><br>
                        <input type="text" class="lname" name="lname" placeholder="Last Name" required><br>
                    </div>

                    <input type="username" class="email2" name="username" placeholder="Username" required><br>
                    <input type="email" class="email2" name="email2" placeholder="Enter Email Address" required><br>
                    <input type="password" class="cpwd" name="cpwd" placeholder="Create a Password" required>
                    
                    <div class="pass">
                        <p>Password must be between 8-16 characters</p>
                        <p>Password can include the following: numbers, letters, !, ., #.</p>
                    </div>
                    
                   <div class="check-box">
                        <input type="checkbox" class="chkbx2" name="chkbx">
                        <label for="chkbx"></label>I agree with Empr Medical's privacy policy.</label><br><br>
                    </div>


                        <button type="submit">Sign Up</button>
            
                </form>
            </div>
            
     </div>

       
</div>
    
</body>
</html>
{% endblock %}
<!-- update -->

users/templates/users/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Red+Hat+Display:wght@400;500;700&display=swap');
    </style>
    <link rel="stylesheet" href= {% static 'users/css/registration.css' %}>
    <link href="https://fonts.google.com/specimen/Lexend+Deca" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" 
          crossorigin="anonymous"/>
    <link rel="icon" href= {% static 'users\images\registration-image\Group.svg' %} type="image/svg+xml">
    <title>Patient Registration Page</title>

</head>
<body>

   <!-- <div class="header">
        <span id="logo">
            <img class="a" src="./images/registration-image/Group.svg">
        </span>
        <div class="text-only">
            <a class="logo-text" href="#" id="nav-logo">Empr Medical</a>
        </div>
    </div>         
    <div class="flex-container">
        <div class="image">
            <img class="doc-img" src="./images/registration-image/Doctor 4.svg">
        </div> -->
        <header>
       
            <div class="navbar">
                <div class="dropdown">
                    <button class="dropbtn">
                        <i class="fas fa-bars fa-2x"></i>
                    </button>
                
                  <div class="dropdown-content">
                        <a href= {% url 'users:index' %}>Home</a>
                        <a href= {% url 'users:about-us' %}>About Us</a>
                        <a href= {% url 'users:faq' %}>FAQ</a>
                        <a href= {% url 'users:user_login' %}>Login</a>
                        <a href= {% url 'users:register' %}>Sign Up</a>
                    
                  </div>
                </div>
            </div>
            
            
            <a class=logo href="index.html">
                <img src= {% static "users/images/FAQ-images/Group.svg" %}>&nbsp;
                <h2>Empr Medical</h2>
            </a>
    
                <div class="no-dropdown">
                        <a href= {% url 'users:index' %}>Home</a>
                        <a href= {% url 'users:about-us' %}>About Us</a>
                        <a href= {% url 'users:faq' %}>FAQ</a>
                        <a href= {% url 'users:user_login' %}>Login</a>
                        <a href= {% url 'users:register' %}>Sign Up</a>
                </div>
                       
            </header>
                    <!-- PATIENT/DOCTOR PAGE TAB -->
                    <div class="tab-switch">
                        <div class="tab-wrapper">
                        <ul>
                            <li class="patient-tab"><a class="patient-link" href= {% url 'users:register' %}>Patient</a></li>
                            <li class="doc-tab"><a class="doc-link" href="doctorregistration.html">Doctor</a></li>
                        </ul>
                        </div>
                    </div>
             <div class="flex-container">
                        <div class="image">
                            <img class="doc-img" src= {% static "users/images/registration-image/Doctor4.svg" %}>
            </div>
                    
            <div class="container">
                <div class="signup-heading">
                    <p>Sign Up</p>
                </div>
        
                <form method="post" action= {% url 'users:register_user' %}>
                {% csrf_token %}


                    <div class="name-container">
                        <input type="text" class="fname" name="fname" placeholder="First Name" required><br>
                        <input type="text" class="lname" name="lname" placeholder="Last Name" required><br>
                    </div>

                    <input type="username" class="fname" name="username" placeholder="User Name" required><br>
                    <input type="email" class="fname" name="email2" placeholder="Enter Email Address" required><br>
                    <input type="password" class="cpwd" name="cpwd" placeholder="Create a Password" required>
                    
                    <div class="pass">
                        <p>Password must be between 8-16 characters</p>
                        <p>Password can include the following: numbers, letters, !, ., #.</p>
                    </div>
                    
                   <div class="check-box">
                        <input type="checkbox" class="chkbx2" name="chkbx">
                        <label for="chkbx"></label>I agree with Empr Medical's privacy policy.</label><br><br>
                    </div>


                        <button type="submit">Sign Up</button>
            
                </form>
            </div>
            
     </div>

       
</div>
    
</body>
</html>
{% endblock %}

<!-- update -->